app = "devops-staging"
primary_region = "ams"

[build]
  image = "x7m7s7/devops:latest"  # استخدام الصورة الجاهزة مباشرة
  # احذف جميع إعدادات البناء الأخرى (dockerfile, buildpacks...)

[http_service]
  internal_port = 8080
  force_https = true

[env]
  PORT = "8080"
  FLASK_ENV = "production"
