app = "devops-staging"

[build]
  image = "x7m7s7/devops:latest"

[http_service]
  internal_port = 8080  # مطابق لـ Dockerfile
  force_https = true
  auto_stop_machines = true

[compute]
  memory = "512mb"
  cpus = 1
  vm_size = "shared-cpu-1x"

[env]
  FLASK_ENV = "production"
  DATABASE_URL = "postgres://user:pass@db.internal:5432"  # مثال لربط DB
