app = "devops-staging"
primary_region = "ams"

[build]
  image = "x7m7s7/devops:latest"  # تأكد أن الصورة موجودة فعلاً في Docker Hub

[http_service]
  internal_port = 8080
  force_https = true

[env]
  PORT = "8080"
