name: Full CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:

  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install requests bandit detect-secrets jq

      - name: Install Trivy (latest)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run SAST
        run: python .github/workflows/scripts/sast.py app.py /tamplates

      - name: Show SAST results
        run: |
          if [ -f sast_results.json ]; then
            cat sast_results.json
          else
            echo "No SAST results file found."
          fi

      - name: Run SCA
        run: python .github/workflows/scripts/sca.py requirements.txt

      - name: Show SCA results
        run: |
          if [ -f sca_results.json ]; then
            cat sca_results.json
          else
            echo "No SCA results file found."
          fi

      - name: Run Secret Scan
        run: python .github/workflows/scripts/secret_scanner.py

      - name: Show Secret Scan results
        run: |
          if [ -f secrets_found.json ]; then
            cat secrets_found.json
          else
            echo "No secrets_found results file found."
          fi

      - name: Run Code Style
        run: python .github/workflows/scripts/code_style.py

      - name: Show Code Style results
        run: |
          if [ -f style_results.json ]; then
            cat style_results.json
          else
            echo "No style results file found."
          fi

      - name: Run Bandit Scan
        run: bandit -r . -f json -o bandit_results.json

      - name: Show Bandit results
        run: |
          if [ -f bandit_results.json ]; then
            cat bandit_results.json
          else
            echo "No bandit results file found."
          fi

      - name: Run Trivy SCA
        run: trivy fs . --scanners vuln --severity HIGH,CRITICAL --format json --output trivy_results.json

      - name: Merge all results
        run: |
          echo "{" > full_report.json
          echo '"sast":' >> full_report.json && (cat sast_results.json || echo '[]') >> full_report.json
          echo ',' >> full_report.json
          echo '"sca":' >> full_report.json && (cat sca_results.json || echo '[]') >> full_report.json
          echo ',' >> full_report.json
          echo '"secrets":' >> full_report.json && (cat secrets_found.json || echo '[]') >> full_report.json
          echo ',' >> full_report.json
          echo '"style":' >> full_report.json && (cat style_results.json || echo '[]') >> full_report.json
          echo ',' >> full_report.json
          echo '"bandit":' >> full_report.json && (cat bandit_results.json || echo '[]') >> full_report.json
          echo ',' >> full_report.json
          echo '"trivy":' >> full_report.json && (cat trivy_results.json || echo '[]') >> full_report.json
          echo "}" >> full_report.json

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: |
            sast_results.json
            sca_results.json
            secrets_found.json
            style_results.json
            bandit_results.json
            trivy_results.json
            full_report.json

      - name: Fail if security issues found
        run: |
          for file in sast_results.json sca_results.json secrets_found.json style_results.json bandit_results.json trivy_results.json; do
            if [ -f "$file" ]; then
              count=$(jq 'if type=="array" then length elif type=="object" then (keys | length) else 0 end' "$file")
              if [ "$count" -gt 0 ]; then
                echo "Security issues detected in $file"
                exit 1
              fi
            fi
          done
          echo "No security issues detected."

  build-and-push:
    needs: security-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.PASS_SECRET }}" | docker login -u "x7m7s7" --password-stdin

      - name: Build Docker Image
        run: docker build -t x7m7s7/devops:latest .

      - name: Push Docker Image
        run: docker push x7m7s7/devops:latest

  deploy-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Deploy to Staging on Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only --app devops-staging

      - name: Run Smoke Test on Staging
        run: python .github/workflows/scripts/smoke_test.py https://devops-staging.fly.dev

  zap-scan:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: https://devops-staging.fly.dev
          fail_action: true
          report_file: zap_report.html
          cmd_options: "-t 60"

      - name: Send ZAP Report via Gmail
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python .github/workflows/scripts/send_email.py

  deploy-production:
    needs: zap-scan
    runs-on: ubuntu-latest
    steps:
      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Deploy to Production on Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only --app devops-production
